config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :users, only: [:index, :show, :create]
  resources :diaries, only: [:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  validates :content, presence: true, length: { maximum: 1000 }
  validates :title, presence: true, length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
      validates :name, presence: true, length: { maximum: 50 }
      validates :email, presence: true, length: { maximum: 255 },
                        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                        uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :diaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :require_user_logged_in
  def index
    @diaries = current_user.diaries.order(id: :desc).page(params[:page])
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def new
    @diary = current_user.diaries.build
  end

  def create
    @diary = current_user.diaries.build(diary_params)
    if @diary.save
      flash[:success] = '投稿しました。'
      redirect_to diaries_path
    else
      flash.now[:danger] = '投稿できませんでした。'
      render :new
    end
  end

  def destroy
  end
  
  private
  
  def diary_params
    params.require(:diary).permit(:title, :content, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to diaries_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/diaries/_diaries.html.erb
<ul class="list-unstyled">
    <% diaries.each do |diary| %>
        <li class"media mb-3">
            <div class="media-body p-3 row border-bottom">
                <div class="col-md-8">
                    <h3><%= link_to diary.title, diary_path(diary) %></h3>
                    <p class="text-muted">投稿日: <%= diary.created_at %></p>
                </div>
                <div class="col-md-4">
                    <% if diary.image? %>
                      <%= image_tag diary.image.url, style: 'max-width: 100%;' %>
                    <% end %>
                </div>
            </div>
        </li>
    <% end %>
    <%= paginate diaries %>
</ul>

app/views/diaries/index.html.erb
<%= render 'diaries/diaries', diaries: @diaries %>

app/views/diaries/new.html.erb
<%= form_with(model: @diary, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control mb-3' %>
    <%= f.label :content, '内容' %>
    <%= f.text_area :content, class: 'form-control', rows: 5 %>
    <%= f.label :image, '画像' %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/diaries/show.html.erb
<h1 class="border-bottom pb-2"><%= @diary.title %></h1>
<%= @diary.created_at %>
<div class="mt-5">
  <p style="white-space: pre-wrap; font-size: 20px; letter-spacing: 0.05em"><%= @diary.content %></p>
</div>
<div>
  <% unless @diary.image.url.nil? %>
    <%= image_tag @diary.image.url, style: 'max-width: 100%;' %>
  <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <%= link_to 'Myブログ', diaries_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Myブログ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body class="bg-light">
    <%= render 'layouts/navbar' %>

    <div class="container bg-white">
      <%= render 'layouts/flash_messages' %>
      <% if logged_in? %>
        <div class="row">
          <div class="col-md-3">
            <ul class="p-3 list-unstyled">
              <% current_user.diaries.each do |diary| %>
                <% unless diary.id.nil? %>
                  <li class="mb-2"><%= link_to diary.title, diary_path(diary) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
          <div class="col-md-6">
            <%= yield %>
          </div>
          <div class="col-md-3 text-center p-3">
            <%= link_to '投稿する', new_diary_path, class:'btn btn-primary' %>
          </div>
       </div>
      <% else %>
        <div>
          <%= yield %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>